# Generated by Django 5.2.5 on 2025-08-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
