# Generated by Django 5.2.5 on 2025-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0002_remove_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField()),
                ('phone_number', models.CharField()),
                ('description', models.CharField()),
            ],
        ),
    ]
