# Generated by Django 5.2.5 on 2025-08-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
