# Generated by Django 5.2.5 on 2025-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0005_alter_store_address_alter_store_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
