# Generated by Django 5.2.5 on 2025-08-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0006_store_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='description',
            new_name='opening_hours',
        ),
    ]
