# Generated by Django 5.2.5 on 2025-09-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0007_rename_description_store_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
