# Generated by Django 5.2.5 on 2025-09-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0009_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
