# Generated by Django 5.2.5 on 2025-09-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0010_remove_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerStoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_store_products', to='grocery_store_app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_store_products', to='grocery_store_app.store')),
            ],
        ),
    ]
