# Generated by Django 5.2.5 on 2025-09-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0012_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address',
        ),
    ]
