# Generated by Django 5.2.5 on 2025-10-01 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0017_order_address_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='per_store_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery_store_app.perstoreproduct'),
        ),
    ]
