# Generated by Django 5.2.5 on 2025-10-22 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store_app', '0018_orderitem_per_store_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='opening_hours',
        ),
        migrations.CreateModel(
            name='StoreOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_open', models.TimeField(default=datetime.time(9, 0))),
                ('monday_close', models.TimeField(default=datetime.time(17, 0))),
                ('tuesday_open', models.TimeField(default=datetime.time(9, 0))),
                ('tuesday_close', models.TimeField(default=datetime.time(17, 0))),
                ('wednesday_open', models.TimeField(default=datetime.time(9, 0))),
                ('wednesday_close', models.TimeField(default=datetime.time(17, 0))),
                ('thursday_open', models.TimeField(default=datetime.time(9, 0))),
                ('thursday_close', models.TimeField(default=datetime.time(17, 0))),
                ('friday_open', models.TimeField(default=datetime.time(9, 0))),
                ('friday_close', models.TimeField(default=datetime.time(17, 0))),
                ('saturday_open', models.TimeField(default=datetime.time(10, 0))),
                ('saturday_close', models.TimeField(default=datetime.time(16, 0))),
                ('sunday_open', models.TimeField(default=datetime.time(10, 0))),
                ('sunday_close', models.TimeField(default=datetime.time(16, 0))),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='grocery_store_app.store')),
            ],
        ),
    ]
